# Generated by Django 3.1.1 on 2020-10-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='host_notmonitor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('owner_login', models.CharField(max_length=10)),
                ('owner_name', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('state', models.IntegerField()),
                ('deleted', models.BooleanField()),
                ('joinTime', models.IntegerField()),
                ('updateTime', models.IntegerField()),
            ],
        ),
    ]
