# Generated by Django 3.1.1 on 2020-10-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0002_auto_20201029_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host_notmonitor',
            name='owner_login',
        ),
        migrations.RemoveField(
            model_name='host_notmonitor',
            name='owner_name',
        ),
        migrations.AddField(
            model_name='host_notmonitor',
            name='owner',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
