# Generated by Django 3.1.1 on 2021-01-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0003_auto_20201029_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExpire',
            fields=[
                ('userid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(max_length=10)),
                ('expiretime', models.DateTimeField()),
                ('manager', models.CharField(max_length=20)),
                ('updatetime', models.DateTimeField()),
                ('createtime', models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='host_notmonitor',
            new_name='HostNotmonitor',
        ),
    ]
