# Generated by Django 3.1.1 on 2021-02-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0005_auto_20210104_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExpire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(max_length=10)),
                ('expiretime', models.DateTimeField()),
                ('manager', models.CharField(default='huy33', max_length=20)),
                ('updatetime', models.DateTimeField()),
                ('createtime', models.DateTimeField()),
            ],
        ),
    ]
