# Generated by Django 3.1.1 on 2021-02-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0006_userexpire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexpire',
            name='expiretime',
            field=models.DateField(),
        ),
    ]
