# Generated by Django 3.1.1 on 2021-02-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0008_auto_20210225_1544'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userexpire',
            index=models.Index(fields=['expiretime'], name='overview_us_expiret_5774cf_idx'),
        ),
    ]
