# Generated by Django 3.1.1 on 2021-02-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0009_auto_20210225_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexpire',
            name='expiretime',
            field=models.DateTimeField(null=True),
        ),
    ]
