# Generated by Django 3.1.1 on 2021-03-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0010_auto_20210225_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='RisTempUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='ristempuser',
            index=models.Index(fields=['userid'], name='overview_ri_userid_529c49_idx'),
        ),
    ]
