# Generated by Django 3.1.1 on 2021-03-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0011_auto_20210301_1030'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ristempuser',
            name='overview_ri_userid_529c49_idx',
        ),
        migrations.RemoveField(
            model_name='ristempuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='ristempuser',
            name='userid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
