# Generated by Django 3.1.1 on 2021-03-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0012_auto_20210301_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexpire',
            name='manager',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
